name: 🐛 Bug report
description: Report a bug or unexpected behavior
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of the bug.
      placeholder: When I do X, I expect Y, but instead Z happens.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Step-by-step instructions to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Where did this bug occur?
      placeholder: |
        - App: web / mobile / tv / backend
        - Branch or version:
        - Environment: dev / staging / prod
        - OS / Browser / Device:
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Logs, screenshots, videos or any extra info.
      render: shell
    validations:
      required: false
