name: ✨ Feature request
description: Suggest a new feature or improvement
labels:
  - enhancement
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is the feature or improvement?
      placeholder: Short description of the feature.
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What problem does this feature solve? What user or team needs it?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: How do you think we should implement this? High-level is fine.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you’ve thought about.
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: Impact and priority
      description: How important is this? What is the impact if we don’t do it soon?
    validations:
      required: false
